// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// LinearGillespie
arma::umat LinearGillespie(int numSim, arma::umat nu, arma::mat a_mat, arma::uvec x0, arma::vec time_vec);
RcppExport SEXP DriftR_LinearGillespie(SEXP numSimSEXP, SEXP nuSEXP, SEXP a_matSEXP, SEXP x0SEXP, SEXP time_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type numSim(numSimSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type a_mat(a_matSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time_vec(time_vecSEXP);
    __result = Rcpp::wrap(LinearGillespie(numSim, nu, a_mat, x0, time_vec));
    return __result;
END_RCPP
}
// Crypt_drift_c
arma::mat Crypt_drift_c(double alpha, double beta, int Ns, arma::vec time_intervals, bool persisting, int splitNum);
RcppExport SEXP DriftR_Crypt_drift_c(SEXP alphaSEXP, SEXP betaSEXP, SEXP NsSEXP, SEXP time_intervalsSEXP, SEXP persistingSEXP, SEXP splitNumSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type Ns(NsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time_intervals(time_intervalsSEXP);
    Rcpp::traits::input_parameter< bool >::type persisting(persistingSEXP);
    Rcpp::traits::input_parameter< int >::type splitNum(splitNumSEXP);
    __result = Rcpp::wrap(Crypt_drift_c(alpha, beta, Ns, time_intervals, persisting, splitNum));
    return __result;
END_RCPP
}
