# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LinearGillespie <- function(numSim, nu, a_mat, x0, time_vec) {
    .Call('DriftR_LinearGillespie', PACKAGE = 'DriftR', numSim, nu, a_mat, x0, time_vec)
}

Crypt_drift_c <- function(alpha, beta, Ns, time_intervals, persisting, splitNum = 0L) {
    .Call('DriftR_Crypt_drift_c', PACKAGE = 'DriftR', alpha, beta, Ns, time_intervals, persisting, splitNum)
}

